<template>
  <ul v-if="backlinks.length" class="space-y-1">
    <li v-for="ref in backlinks" :key="ref.slug">
      <NuxtLink :to="ref.path" class="block rounded px-2 py-2 hover:bg-(--ui-bg-elevated)">
        <div class="truncate text-[13px] font-medium text-(--ui-text)">{{ ref.title }}</div>
        <div
          class="wiki-backlink-snip mt-0.5 text-[11.5px] leading-snug text-(--ui-text-muted) italic"
        >
          <template v-for="(seg, i) in parseHighlight(ref.snippet)" :key="i">
            <mark v-if="seg.highlight">{{ seg.text }}</mark>
            <template v-else>{{ seg.text }}</template>
          </template>
        </div>
      </NuxtLink>
    </li>
  </ul>
</template>

<script setup lang="ts">
import type { WikiBacklinkRef, WikiBacklinksMap } from '#shared/types/wiki'
import { parseHighlight } from '~/utils/snippet-highlight'

const props = defineProps<{ slug: string }>()
const emit = defineEmits<{ count: [n: number] }>()

// The backlinks artefact is generated by modules/wiki-slug-index/index.ts.
// Loading via useAsyncData means: on prerender the server reads the JSON, the
// asyncData function returns ONLY the slice for this slug, and only the slice
// ends up in the route's _payload.json. The full map is never bundled into
// the client. In dev, the cache opt-out re-runs the function on soft nav
// (Pitfall #11) and Vite serves the JSON on demand.
const { data: backlinks } = await useAsyncData<WikiBacklinkRef[]>(
  () => `backlinks-${props.slug}`,
  async () => {
    const mod = await import('#build/wiki-backlinks.json')
    const map =
      (mod as unknown as { default?: WikiBacklinksMap }).default ??
      (mod as unknown as WikiBacklinksMap)
    return map.byTarget[props.slug] ?? []
  },
  {
    default: () => [],
    watch: [() => props.slug],
    ...(import.meta.dev ? { getCachedData: () => undefined } : {}),
  },
)

watchEffect(() => emit('count', backlinks.value.length))
</script>
